# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'Training Subscription(743e6b7c-615e-48d2-9176-4405133b7246)'
#     appType: 'webAppLinux'
#     appName: 'xunil2'
#     package: '$(System.DefaultWorkingDirectory)/**/*.zip'
#     runtimeStack: 'DOTNETCORE|6.0'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Training Subscription(743e6b7c-615e-48d2-9176-4405133b7246)'
    appType: 'webAppLinux'
    WebAppName: 'xunil'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'DOTNETCORE|6.0'
    DeploymentType: zipDeploy
    